### ISSUE TITLE
SSL Keys alternative --> create new user for pivpn-web?

### ISSUE THREAD

**Issue by Kopernikus1979** [WeeJeWel/pivpn-web#10]
Hi,

I have two RaspPi running Pivpn and pivpn-web seems the missing piece...
However I access both my Pihole's with SSL keys instead of username/password.
Since pivpn-web doesn't supprot SSL keys (yet?) I was wondering if I could create a second user/pass just for the purpose of acessing the pivpn-web, also what user rights would it need (or you suggest) so pivpn-web is working without compromising 
security?

Alternative I could also install pivpn-web on my Synology-NAS and connect through SSL.

Thx!

**Comment by WeeJeWel** [comment]
Yes that would work. Just add it to the right group (I think pivpn).

**Comment by WeeJeWel** [comment]
Hey guys! PiVPN Web has been archived, and its successor is [wg-easy](https://github.com/WeeJeWel/wg-easy).

It is a much better and simpler solution because it has WireGuard pre-installed, next to the Web UI you're familiar with. Additionally, you can set a custom password, so no more SSH dependency.
