### ISSUE TITLE
invalid client when adding new user

### ISSUE THREAD

**Issue by galiehneh** [WeeJeWel/pivpn-web#11]
hi Dev,

im using Ubuntu 20.04.2 LTS x86_64, succesfully installed pivpn-web , install latest pivp with wireguard, but cant add new user via pivpn-web, it says: "Invalid Client".

please help, thanks.

**Comment by WeeJeWel** [comment]
What's inside `/etc/wireguard/configs/clients.txt`?

**Comment by simonlerpard** [comment]
I stumbled into this myself. In ubuntu the default behavior of sudo is to ask for the user's password. In Raspbian, the default behavior doesn't, and this project does not (currently?) handle a password prompt at all. 😜 

@galiehneh Remove the password prompt and that should solve your issue I guess. Here's a short guide on how to do that:
[https://www.cyberciti.biz/faq/linux-unix-running-sudo-command-without-a-password/](https://www.cyberciti.biz/faq/linux-unix-running-sudo-command-without-a-password/)

**Comment by WeeJeWel** [comment]
Hey guys! PiVPN Web has been archived, and its successor is [wg-easy](https://github.com/WeeJeWel/wg-easy).

It is a much better and simpler solution because it has WireGuard pre-installed, next to the Web UI you're familiar with. Additionally, you can set a custom password, so no more SSH dependency.
