### ISSUE TITLE
no publickey authentication support

### ISSUE THREAD

**Issue by JakeFrosty** [WeeJeWel/pivpn-web#13]
i wanted to try this docker container but unfortunately it does not support publickey authentication, any ideas how to authenticate via publickey method?

**Comment by WeeJeWel** [comment]
That is not supported at the moment. Feel free to make a PR.

**Comment by WeeJeWel** [comment]
Hey guys! PiVPN Web has been archived, and its successor is [wg-easy](https://github.com/WeeJeWel/wg-easy).

It is a much better and simpler solution because it has WireGuard pre-installed, next to the Web UI you're familiar with. Additionally, you can set a custom password, so no more SSH dependency.
