### ISSUE TITLE
Listing existing clients

### ISSUE THREAD

**Issue by Parlendir** [WeeJeWel/pivpn-web#2]
Hi,
Installed as a docker-compose container.
The pivpn/wireguard is installed on another server (Docker is on a nas, pivpn on a rpi).
Running the container with the environment SSH_HOST=<rpi ip>
I can log on with the id/pw of the rpi.
But the pivpn-web is empty instead of showing the 4 clients created within pivpn server : I thought it wuold show pre existing clients.

**Comment by WeeJeWel** [comment]
It should. Any useful errors?

**Comment by WeeJeWel** [comment]
v1.1.0 should now show an alert if an error occurs.

**Comment by WeeJeWel** [comment]
Hey guys! PiVPN Web has been archived, and its successor is [wg-easy](https://github.com/WeeJeWel/wg-easy).

It is a much better and simpler solution because it has WireGuard pre-installed, next to the Web UI you're familiar with. Additionally, you can set a custom password, so no more SSH dependency.
