### ISSUE TITLE
Webinterface not working

### ISSUE THREAD

**Issue by peddaahh** [WeeJeWel/pivpn-web#5]
If you require the user to put in the password everytime needed in 
`/etc/sudoers.d/010_pi-nopasswd` --> `NOPASSWD: = ALL` is replaced by `PASSWD: ALL`
for security reasons

this means for example `pivpn -c` requires the password to be put in again. the webinterface can't handle that

**Comment by WeeJeWel** [comment]
Thanks for the issue, but I don't think there's a great way to change that.

Maybe you can add a dedicated pivpn-web user that has permission to run sudo without password.

**Comment by peddaahh** [comment]
Sure that's a good workaround.
Just in case others have that problem too ;)

**Comment by WeeJeWel** [comment]
Hey guys! PiVPN Web has been archived, and its successor is [wg-easy](https://github.com/WeeJeWel/wg-easy).

It is a much better and simpler solution because it has WireGuard pre-installed, next to the Web UI you're familiar with. Additionally, you can set a custom password, so no more SSH dependency.
